apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-account
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  ORDER_REGION: "us-east-1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      serviceAccountName: order-service-account
      containers:
      - name: order
        image: saikumarnerella90/order-service:latest
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: order-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - port: 3002
      targetPort: 3002
