apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-account
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  LOG_LEVEL: "info"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      serviceAccountName: product-service-account
      containers:
      - name: product
        image: saikumarnerella90/product-service:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: product-config
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product
  ports:
    - port: 3001
      targetPort: 3001
